# Demo to see how to load another file
- name: Demo to load another file
  hosts: all
  tasks:
    -name: Print Hello World
    ansible.builtin.debug:
      msg: "Hello World"

    - name: Include universe file
      ansible.builtin.include_tasks:                                #Include task fuction to include universe.yml file
        file: universe.yml                                          #In Universe.yml file we have given a print message, the main
                                                                    # Objective of this function is to capture the information from the universe file.