- name: Print Parameters
  hosts: localhost
  connection: local
  tasks:
    - name: Print Parameters
      ansible.builtin.debug:
        msg: Parameter - {{lookup('amazon.aws.aws.ssm', 'test.test', region='us-east-1')}}
