
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: saty.fun
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://saty.fun/saty.fun
  dnsZone: saty.fun
  etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: control-plane-us-east-1a
          name: a
      manager:
        backupRetentionDays: 90
      memoryRequest: 100Mi
      name: main
    - cpuRequest: 100m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: control-plane-us-east-1a
          name: a
      manager:
        backupRetentionDays: 90
      memoryRequest: 100Mi
      name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
    - 0.0.0.0/0
    - ::/0
  kubernetesVersion: 1.28.11
  masterPublicName: api.saty.fun
  networkCIDR: 192.168.0.0/16
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    - 0.0.0.0/0
    - ::/0
  subnets:
    - cidr: 192.168.1.0/24
      name: us-east-1a
      type: Public
      zone: us-east-1a
    - cidr: 192.168.2.0/24
      name: us-east-1b
      type: Public
      zone: us-east-1b
  topology:
    dns:
      type: Public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: saty.fun
  name: control-plane-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240607
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 10
  subnets:
    - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: saty.fun
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240607
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  rootVolumeSize: 10
  subnets:
    - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: saty.fun
  name: nodes-us-east-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240607
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  rootVolumeSize: 10
  subnets:
    - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: SSHCredential
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: saty.fun
  name: admin
spec:
  publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzhE6tVR8fRUa6NPr7qLqewYTG/ydJP9dzZP75/0WXAGwfHZ3dWWte3J8vouqmD7iMhSFjecQG+Tkr13mgPTeD4V1/sV3IRb9blWPuW5M235bMlCqwv25jHeb6r21dANb8CMMVrY5Za00Do90dET1vekulArrso89wCiHB6Ekw7UR8y9eNPi2v5VO+Kkcdy2oocrwWWhOhkH/+tG3K/U4v4fISpxz/o5QCzcDDF5OVaW05QO6wA81XG8wdJJIgJUAokJWwCV4B/X4vBuoEpojHjTR8iHPIpVSuel7WK7Is763bCXKc/3/MUZXkfIb3Gl2tsFhYZ+UNjlkURWQmpSU1+mDvQr6qdIFEHKszSSHCWr/CZQdTr7TiLu/g6bmSScniIVMzvXgYcd78fY/qrDrLrR+FUFm8ZyBR3M0NalQXY24Cmdrs+6P1WcCY5vWPsy55FdIomEN3C6Zo0BPTQjCfECnXoci4R3T6V1Uj6L7zVrkmYfRpMuh2tYIuMbNuE9U=
    root@ip-172-31-81-35.ec2.internal
