- name: Demo on Loops
  hosts: local
  connection: local
  tasks:
    - name: Print fruit name
      ansible.builtin.debug:
        msg: "Fruit: {{ item }}"
      loop:
        - apple
        - orange
        - banana
    - name: Print fruit name with quantity
      ansible.builtin.debug:
        msg: "Fruit: {{ item.name }}, Quantity: {{ item.quantity }}"
      loop:
        - [name: "apple", quantity: 2]
        - [name: "orange", quantity: 3]
        - [name: "banana", quantity: 1]