
apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: saty.fun
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://saty.fun/saty.fun
  dnsZone: saty.fun
  etcdClusters:
    - cpuRequest: 200m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: control-plane-us-east-1a
          name: a
      manager:
        backupRetentionDays: 90
      memoryRequest: 100Mi
      name: main
    - cpuRequest: 100m
      etcdMembers:
        - encryptedVolume: true
          instanceGroup: control-plane-us-east-1a
          name: a
      manager:
        backupRetentionDays: 90
      memoryRequest: 100Mi
      name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
    - 0.0.0.0/0
    - ::/0
  kubernetesVersion: 1.28.15
  masterPublicName: api.saty.fun
  networkCIDR: 192.168.0.0/16
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
    - 0.0.0.0/0
    - ::/0
  subnets:
    - cidr: 192.168.1.0/24
      name: us-east-1a
      type: Public
      zone: us-east-1a
    - cidr: 192.168.2.0/24
      name: us-east-1b
      type: Public
      zone: us-east-1b
  topology:
    dns:
      type: Public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: saty.fun
  name: control-plane-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20241113
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 10
  subnets:
    - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: saty.fun
  name: nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20241113
  machineType: t3.medium
  maxSize: 2
  minSize: 2
  role: Node
  rootVolumeSize: 10
  subnets:
    - us-east-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: saty.fun
  name: nodes-us-east-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20241113
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  rootVolumeSize: 10
  subnets:
    - us-east-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: SSHCredential
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: saty.fun
  name: admin
spec:
  publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDFlzh24X/XCx0L0++goFKkktAPfWNhWv1/41wJUMH1iCrNVQEJXY1173W4yS4x3ZYB91TnRjl9oKq415RYJe0NXZRqbuPXKWUzBkidS7/6OsHVFguHp1o330oSN3gNw0xaJ0NaOf+BR73j6OJbF7Dz/ph1dGg+M+OJCvOnPX4k44wgzf7sjtgrtFpXCsOh/gh1OQxW02+eejH0c3imsqT0g0Q8Z76weDh/BYQd5M33vq9FMBiqj1SbeHO55yiRTfi3a+HpfTuTtRcAfVZGD9M5OB35i+eragXpmOh+loBZsgzIcHpOy1+RpkZU3Ih4Ru12KAjtun4y9t1BAvZCrvcF+fVdZWif7JXOo49jYgJpsQRZtVgbEOKZ4xPkJvqjumdKP5BdG0zzoW9IGraPeM1c/WFwaEzwLRjhOt/KS38M/xQL2lx5mjQHd3V2W4d7ujeMyEvNYRB7ZrHVyXBFVoQ5So0C0mLrzPcMbceq3t4cBFm+iMJ+VSikObHc6Vi1HbE=
    root@ip-172-31-83-43.ec2.internal