apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv1
  labels:
    type: aws-pv1
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-013b899889f718e40
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv2
  labels:
    type: aws-pv2
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-01b3211338f7cd01b
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv3
  labels:
    type: aws-pv3
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0cf02648427def02a
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv4
  labels:
    type: aws-pv4
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0fe45a72925130e49
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv5
  labels:
    type: aws-pv5
spec:
  storageClassName: gp2
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0d47e81561e4a9057
    fsType: ext4