apiVersion: v1
kind: Secret
metadata:
  name: aws-creds-in-file
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id: 
    aws_secret_access_key: 


# Mount AWS credentials as a volume


---
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod1
spec:
  containers:
  - name: aws-cli-container
    image: navieng/troubleshootingtools:v1
    volumeMounts:
      - name: secret-volume
        mountPath: /root/.aws/credentials
        subPath: credentials
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: aws-creds-in-file